### ISSUE TITLE
Lagom 1.6.1 stops working on example

### ISSUE THREAD

**Issue by scalamat** [pac4j/lagom-pac4j-scala-demo#4]
Hi,
I have to secure my service. I found this example. 
I set all up you described. After runAll and after call my authenticate get call with my browser my test app crashs!
```
Uncaught error from thread [security-impl-application-akka.actor.default-dispatcher-18]: org.pac4j.core.client.Clients.findClient(Ljava/lang/String;)Lorg/pac4j/core/client/Client;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[security-impl-application]
java.lang.NoSuchMethodError: org.pac4j.core.client.Clients.findClient(Ljava/lang/String;)Lorg/pac4j/core/client/Client;
        at org.pac4j.lagom.scaladsl.SecuredService.$anonfun$authenticate$1(SecuredService.scala:59)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$.$anonfun$compose$1(ServerServiceCall.scala:145)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$$anon$4.invokeWithHeaders(ServerServiceCall.scala:113)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$$anon$2.invokeWithHeaders(ServerServiceCall.scala:73)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$$anon$1.invoke(ServerServiceCall.scala:55)
        at com.lightbend.lagom.internal.scaladsl.server.ScaladslServiceRouter.invokeServiceCall(ScaladslServiceRouter.scala:115)
        at com.lightbend.lagom.internal.scaladsl.server.ScaladslServiceRouter.invokeServiceCall(ScaladslServiceRouter.scala:28)
        at com.lightbend.lagom.internal.server.ServiceRouter.$anonfun$handleServiceCall$1(ServiceRouter.scala:222)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:167)
        at scala.util.Try$.apply(Try.scala:210)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:167)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:198)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:412)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
11:53:08.189 [error] akka.actor.ActorSystemImpl [akkaAddress=akka://security-impl-application@127.0.0.1:53371, sourceThread=security-impl-application-akka.actor.default-dispatcher-18, akkaSource=akka.actor.ActorSystemImpl(security-impl-application), sourceActorSystem=security-impl-application, akkaTimestamp=09:53:08.182UTC] - Uncaught error from thread [security-impl-application-akka.actor.default-dispatcher-18]: org.pac4j.core.client.Clients.findClient(Ljava/lang/String;)Lorg/pac4j/core/client/Client;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[security-impl-application]
java.lang.NoSuchMethodError: org.pac4j.core.client.Clients.findClient(Ljava/lang/String;)Lorg/pac4j/core/client/Client;
        at org.pac4j.lagom.scaladsl.SecuredService.$anonfun$authenticate$1(SecuredService.scala:59)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$.$anonfun$compose$1(ServerServiceCall.scala:145)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$$anon$4.invokeWithHeaders(ServerServiceCall.scala:113)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$$anon$2.invokeWithHeaders(ServerServiceCall.scala:73)
        at com.lightbend.lagom.scaladsl.server.ServerServiceCall$$anon$1.invoke(ServerServiceCall.scala:55)
        at com.lightbend.lagom.internal.scaladsl.server.ScaladslServiceRouter.invokeServiceCall(ScaladslServiceRouter.scala:115)
        at com.lightbend.lagom.internal.scaladsl.server.ScaladslServiceRouter.invokeServiceCall(ScaladslServiceRouter.scala:28)
        at com.lightbend.lagom.internal.server.ServiceRouter.$anonfun$handleServiceCall$1(ServiceRouter.scala:222)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:167)
        at scala.util.Try$.apply(Try.scala:210)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:167)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:198)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:412)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
11:53:08.194 [info] play.core.server.AkkaHttpServer [] - Stopping server...
```

Sorry this does not make sense. On testing it in my application loader i get the client
```
trait SecurityServiceComponents extends LagomServerComponents with CassandraPersistenceComponents {
  implicit def executionContext: ExecutionContext
  def environment: Environment

  implicit def materializer: Materializer
  implicit def c: Config = this.configuration.underlying


  /**
   * PAC4J client.
   * See <a href="http://www.pac4j.org/3.4.x/docs/clients.html">PAC4J documentation</a> for more information about PAC4J clients.
   * https://github.com/pac4j/lagom-pac4j
   * https://github.com/pac4j/lagom-pac4j-scala-demo/blob/master/impl/src/main/scala/org/pac4j/lagom/demo/impl/AuthJwtLoader.scala
   */
  lazy val jwtClient: HeaderClient = {
//    new HeaderClient(AUTHORIZATION_HEADER,BEARER_HEADER_PREFIX,JwtAuthenticatorHelper.parse(c.getConfig("pac4j.lagom.jwt.authenticator")))


    val headerClient = new HeaderClient
    headerClient.setHeaderName(AUTHORIZATION_HEADER)
    headerClient.setPrefixHeader(BEARER_HEADER_PREFIX)
    // Strongly recommendation use `JwtAuthenticatorHelper` for initializing `JwtAuthenticator`.
    headerClient.setAuthenticator(JwtAuthenticatorHelper.parse(c.getConfig("pac4j.lagom.jwt.authenticator")))
    // Custom AuthorizationGenerator to compute the appropriate roles of the authenticated user profile.
    // Roles are fetched from JWT 'roles' attribute.
    // See more http://www.pac4j.org/3.4.x/docs/clients.html#2-compute-roles-and-permissions
    import scala.jdk.OptionConverters._
    headerClient.setAuthorizationGenerator((ctx: WebContext, profile: UserProfile) => {

      println("DANKE!!!!")
      println(ctx.getRemoteAddr)
      println(profile.getUsername)
      None.toJava
      Some(profile).toJava
//      profile.containsAttribute("roles")
//      if (profile.containsAttribute("roles")) profile.addRoles(profile.getAttribute("roles").asInstanceOf[java.util.Collection[String]])
//      Some(profile).toJava
    })
    headerClient.setName("jwt_header")
    headerClient
  }

  lazy val serviceConfig: org.pac4j.core.config.Config = {
    val config = new org.pac4j.core.config.Config(jwtClient)
    config.getClients.setDefaultSecurityClients(jwtClient.getName)
    config
  }

  println(
    s"""
       |VERWIRRUNG ACHTUNG!!!!!!
       |${jwtClient.getName}
       |${jwtClient.getHeaderName}
       |${jwtClient.getPrefixHeader}
       |--------------------------------------
       |${serviceConfig.getClients}
       |${serviceConfig.getAuthorizers}
       |${serviceConfig.getSessionStore}
       |######################################
       |${Try(serviceConfig.getClients.findClient("ANDRÉ"))}
       |""".stripMargin)


  override lazy val lagomServer = serverFor[SecurityService](wire[SecurityServiceImpl])
  lazy val jsonSerializerRegistry = SecurityServiceSerializerRegistry
  private implicit val mode = environment.mode

  //Entities
  persistentEntityRegistry.register(wire[PermissionEntity])
  persistentEntityRegistry.register(wire[SessionEntity])

  //Event Processors
  readSide.register(wire[SessionSchedulerProcessor])
  wire[SessionScheduler]

  //Repos
  lazy val sessionRepository = wire[SessionRepository]
}
```

The result:
```
11:59:01.222 [info] akka.cluster.Cluster [akkaRemoteAddressUid=3932741438238065669, akkaAddress=akka://security-impl-application@127.0.0.1:54621, sourceThread=security-impl-application-akka.actor.internal-dispatcher-7, akkaSource=Cluster(akka://security-impl-application), sourceActorSystem=security-impl-application, akkaRemoteAddress=akka://security-impl-application@127.0.0.1:54621, akkaTimestamp=09:59:01.222UTC, akkaMemberStatus=Up] - Cluster Node [akka://security-impl-application@127.0.0.1:54621] - Leader is moving node [akka://security-impl-application@127.0.0.1:54621] to [Up]

VERWIRRUNG ACHTUNG!!!!!!
jwt_header
Authorization
Bearer
--------------------------------------
#Clients# | callbackUrl: null | clients: [#HeaderClient# | name: jwt_header | headerName: Authorization | prefixHeader: Bearer  | extractor: null | authenticator: #JwtAuthenticator# | signatureConfigurations: [#SecretSignatureConfiguration# | secret: [protected] | algorithm: HS256 |, #RSASignatureConfiguration# | keys: [protected] | algorithm: RS256 |, #ECSignatureConfiguration# | keys: [protected] | algorithm: ES256 |] | encryptionConfigurations: [#SecretEncryptionConfiguration# | secret: [protected] | algorithm: dir | method: A256GCM |, #RSAEncryptionConfiguration# | keys: [protected] | algorithm: RSA-OAEP-256 | method: A128GCM |, #ECEncryptionConfiguration# | keys: [protected] | algorithm: ECDH-ES+A256KW | method: A256GCM |] | realmName: authentication required | identifierGenerator: null | | profileCreator: org.pac4j.core.profile.creator.AuthenticatorProfileCreator@61392331 |] | ajaxRequestResolver: null | callbackUrlResolver: null | authorizationGenerators: [] | defaultSecurityClients: jwt_header | urlResolver: null |
{}
null
######################################
Success(Optional.empty)

11:59:01.317 [info] akka.cluster.sharding.ShardRegion [akkaAddress=akka://security-impl-application@127.0.0.1:54621, sourceThread=security-impl-application-akka.actor.internal-dispatcher-4, akkaSource=akka://security-impl-application@127.0.0.1:54621/system/sharding/PermissionEntity, sourceActorSystem=security-impl-application, akkaTimestamp=09:59:01.317UTC] - PermissionEntity: Idle entities will be passivated after [2.000 min]
```

Also I have a problem with the implementation. I copied the SecuredService to implement it again to find out WHERE probles with abstract methods could be. That points also in a number other problems. And this line in SecuredService:59 seemes to be wrong.
```
val defaultClient = clients.findClient(clientName).asInstanceOf[Client[Credentials, CommonProfile]]
```
clients.findClient is a Optional. a cast without a get must be throw an error?

Please can you help to write a really working example?

**Comment by scalamat** [comment]
Ok find the problem!
I am using pac version 4.0.0 but this example is for 3.6.1
